[project]
name = "raingourd-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "google-adk>=2.7.0",
    "uvicorn>=0.52.3",
]

[project.scripts]
raingourd-ai = "raingourd_ai:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
